version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "test/**"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "test/**"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "test/**"
